version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm i npm@latest -g
      - npm i typescript@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - npm install --unsafe-perm=true --allow-root --legacy-peer-deps
  build:
    commands:
      - npm run prod
artifacts:
  files:
    - "**/*"
  name: test-server-$(date +%Y-%m-%d)
